# code: language=ansible
---

- name: "PHP | Always | Install dependencies | Dnf"
  ansible.builtin.dnf:
    name: "{{ php_always_packages }}"
    state: present
    update_cache: true
  become: true
  tags:
    - always
