# code: language=ansible
---

# Check distribution and version before run tasks

- name: "PHP | Always | Check distribution"
  ansible.builtin.fail:
    msg: "Unsupported distribution {{ dist_name }}"
  when:
    - dist_name not in ["alma", "centos", "debian", "oracle", "rocky", "ubuntu"]
  tags:
    - always

- name: "PHP | Always | Check alma/centos/oracle/rocky linux versions"
  ansible.builtin.fail:
    msg: "Unsupported distribution version {{ dist_name }}: {{ dist_version }}"
  when:
    - dist_name in ["alma", "centos", "oracle", "rocky"]
    - dist_version not in ["8", "9"]
  tags:
    - always

- name: "PHP | Always | Check Debian / Ubuntu codenames"
  ansible.builtin.fail:
    msg: "Unsupported distribution version {{ dist_name }}: {{ dist_codename }}"
  when:
    - dist_name in ["debian", "ubuntu"]
    - dist_codename not in ["buster", "bullseye", "bookworm", "focal", "jammy"]
  tags:
    - always

# Include distribution specified vars

- name: "PHP | Always | Include distribution vars"
  ansible.builtin.include_vars: "{{ dist_name }}.yml"
  tags:
    - always

# Install role packages dependencies

- name: "PHP | Always | Install packages"
  ansible.builtin.include_tasks: "always/install/{{ dist_pkg_mgr }}.yml"
  when:
    - php_always_packages | is_ne_list
  tags:
    - always
